refactor: upgrade to nock 13 (#2617)
* refactor: upgrade to nock 11. Getting one failing test that doesn't use nock...
AssertionError: expected 'We couldn\'t find an app-ci.json file in the current directory, and your app.json already has the environments key.\nYou\'re all set! 🎉\n' to equal 'We couldn\'t find an app-ci.json file in the current directory, but we\'re creating a new app.json manifest for you.\nPlease check the contents of your app.json before committing to your repo.\nYou\'re all set! 🎉\n'
<Click to see difference>

    at Context.<anonymous> (test/unit/commands/ci/migrate-manifest.unit.test.ts:140:25)

* chore: add a script for just running tests to avoid building every time.
The test error in the last commit was from running multiple test process at once and a file did not get deleted.

* fix: test script

* upgrade to nock 13

* fix: uncomment some expects that now pass after nock upgrade